### ISSUE TITLE
Starting puma on staging reads wrong state_path

### ISSUE THREAD

**Issue by cenotaph** [ahmadsherif/capistrano-puma#3]
Hi,

Running two apps on the same server, one in production and one in staging. "cap staging puma:start" claims that puma is already running, but it's trying to read the state file from the production instance.  The puma.rb on the server explicitly specifies the staging state_path and I also defined in my config/deploy/staging.rb 

> set :state_path, '/var/www/staging/shared/tmp/pids/puma.state'

for good measure. If I try a restart I see in the output:

> 01 ~/.rvm/bin/rvm 2.4.2 do bundle exec pumactl -S /var/www/production/shared/tmp/pids/puma.state -F /var/www/staging/shared/puma.rb restart

so it's clearly getting the puma.state line from somewhere, incorrectly.

**Comment by ahmadsherif** [comment]
Hi @cenotaph, this repo has been unmaintained for years, and I'm surprised it's being used anywhere. Puma docs suggests using [this gem](https://github.com/seuros/capistrano-puma) which seems to be actively maintained, so I think you should be using it instead.

I'll add a deprecation notice to this repo to avoid wasting anyone's time, and sorry if I wasted yours.

Cheers!
